### ISSUE TITLE
Excluded From Hacktoberfest 2022

### ISSUE THREAD

**Issue by divyansh-ag-03** [ishaangupta-YB/Hacktoberfest-2022#269]
The PR I launched is showing the 'Excluded' tag under the repo.

**Comment by sayskar500** [comment]
Yeah that seems to be happening with almost all DSA type repos

**Comment by ishaangupta-YB** [comment]
> The PR I launched is showing the 'Excluded' tag under the repo.

Yeah i know. I am in talks with the team, till then you can contribute in other repos.

**Comment by ItzLevvie** [comment]
> Yeah that seems to be happening with almost all DSA type repos

@sayskar500: A lot of repositories under the `hacktoberfest` topic are being monitored by various folks due to the increase of abuse of how the system behind Hacktoberfest 2022 works.

I regularly work with the team behind Hacktoberfest 2022 to ensure **_quality contributions_** from various contributors around the world.

For Data Structures and Algorithms (DSA) repositories, we tend to lean more on the **_exclusion_** side as most of the contributions towards these repositories are either low-quality, copied from somewhere else, or used as a way to increase pull request count for Hacktoberfest 2022. We feel that this does not lead to what we call a **_quality contribution_**.

That being said we can all agree that quality over quantity matters a lot for repository maintainers. I don't make the rules here as those decisions are made by DigitalOcean by themselves.

We also find it unfair for those who have made **_quality_** contributions only to be overtaken by contributors who create contributions that have no value towards the project that they contribute to which is why these rules tend to get stricter over the years.

---

I took a look at this repository, and unfortunately, it will not be able to qualify for Hacktoberfest 2022 due to the reasons mentioned above. Not only was it created very recently for Hacktoberfest 2022 rather than being an existing repository, but when we take a look at the accepted contributions, they don't fall in line with what we call a **_quality contribution_**.

While this repository was created to allow contributors to make their first contributions on GitHub, it does so with very little effort.

If you feel the exclusion was a mistake, then please reach out to the team behind Hacktoberfest 2022 for an extensive, manual review of this repository.

We take each exclusion very seriously on our side. We manually review as many of the excluded repositories as possible to reduce the possibility of a false exclusion.

**Comment by sayskar500** [comment]
Noted @ItzLevvie. Thanks for explaining to us the main reason behind the exclusion of the repository. It's just that it would be great if the DigitalOcean team could exclude such repositories even before starting the hacktoberfest. 

I understand the volume is huge and hence difficult to detect such repositories at first glance. But it shall be great if from next point onwards some kind of check/verification can be kept to avoid such situations.
